version: "3.9"
services:
    frontend:
        image: ${REGISTRY}/pet-frontend:${IMAGE_TAG}
        environment:
            REACT_APP_AUTH_URL: https://api.herman.team
        networks:
            - traefik-public
            - default
        deploy:
            labels:
                - traefik.enable=true
                - traefik.docker.network=traefik-public
                - traefik.http.routers.frontend.rule=Host(`herman.team`) || Host(`www.herman.team`)
                - traefik.http.services.frontend.loadBalancer.server.port=80
                - traefik.http.middlewares.frontend-redirect.redirectRegex.regex=^(https?://)www.herman.team/(.*)$$
                - traefik.http.middlewares.frontend-redirect.redirectRegex.replacement=$${1}demo-auction.deworker.pro/$${2}
                - traefik.http.middlewares.frontend-redirect.redirectRegex.permanent=true
                - traefik.http.routers.frontend.middlewares=frontend-redirect,secure-headers
                - traefik.http.routers.frontend.entryPoints=https
                - traefik.http.routers.frontend.tls=true
                - traefik.http.routers.frontend.tls.certResolver=letsEncrypt
            mode: replicated
            replicas: 2
            update_config:
                parallelism: 1
                delay: 10s

    react:
        image: ${REGISTRY}/pet-react:${IMAGE_TAG}
        environment:
            REACT_APP_AUTH_URL: https://api.herman.team
        networks:
            - traefik-public
            - default
        deploy:
            labels:
                - traefik.enable=true
                - traefik.docker.network=traefik-public
                - traefik.http.routers.react.rule=Host(`react.herman.team`) || Host(`www.react.herman.team`)
                - traefik.http.services.react.loadBalancer.server.port=80
                - traefik.http.middlewares.react-redirect.redirectRegex.regex=^(https?://)www.react.herman.team/(.*)$$
                - traefik.http.middlewares.react-redirect.redirectRegex.replacement=$${1}react.herman.team/$${2}
                - traefik.http.middlewares.react-redirect.redirectRegex.permanent=true
                - traefik.http.routers.react.middlewares=react-redirect,secure-headers
                - traefik.http.routers.react.entrypoints=https
                - traefik.http.routers.react.tls=true
                - traefik.http.routers.react.tls.certResolver=letsEncrypt
            mode: replicated
            replicas: 2
            update_config:
                parallelism: 1
                delay: 10s

    api:
        image: ${REGISTRY}/pet-api:${IMAGE_TAG}
        networks:
            - traefik-public
            - default
        deploy:
            labels:
                - traefik.enable=true
                - traefik.docker.network=traefik-public
                - traefik.http.routers.api.rule=Host(`api.herman.team`)
                - traefik.http.services.api.loadBalancer.server.port=80
                - traefik.http.routers.api.middlewares=secure-headers
                - traefik.http.routers.api.entryPoints=https
                - traefik.http.routers.api.tls=true
                - traefik.http.routers.api.tls.certResolver=letsEncrypt
            mode: replicated
            replicas: 2
            update_config:
                parallelism: 1
                delay: 5s

    api-php-fpm:
        image: ${REGISTRY}/api-php-fpm:${IMAGE_TAG}
        environment:
            APP_ENV: prod
            APP_DEBUG: 0
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 5s

    api-php_cli:
        image: ${REGISTRY}/api-php-cli:${IMAGE_TAG}
        environment:
            APP_ENV: prod
            APP_DEBUG: 0
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 5
                window: 120s

volumes:
    api-postgres:

networks:
    traefik-public:
        external: true